Created NewStart
MateussXimeness/computer-graphics pull request #11
Opened 2022-02-17 18:58 UTC by MateussXimeness

2022-02-17 21:28 UTC, hiagochagas requested changes
tem um arquivo .rar em src/Scenes

2022-02-17 21:28 UTC, hiagochagas commented on project.godot
>  "deadzone": 0.5,
Todas essas alterações não geram problemas na movimentação do personagem? @pedro0x53

2022-02-18 12:03 UTC, pedro0x53 commented on project.godot
>  "deadzone": 0.5,
Causam sim, não tem mais nenhum comando funcionando (movimentação, ataque e defesa), mas se manter o antigo funciona, é só ter cuidado no merge.

2022-02-18 21:54 UTC, hiagochagas approved these changes
Todas as mudanças foram feitas e o player pode se movimentar normalmente

2022-02-18 22:02 UTC, pedro0x53 approved these changes

2022-02-18 22:03 UTC, hiagochagas approved these changes

2022-02-18 22:03 UTC, merged